name: Deploy FortiHex

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:push -a YOUR_HEROKU_APP_NAME backend
          heroku container:release -a YOUR_HEROKU_APP_NAME backend

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod--token YOUR_VERCEL_TOKEN_NAME
