version: "3.8"
services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
      enviroment:
        -FLASK_ENV=production
      restart: always

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
